//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for COBPolicyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="COBPolicyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.healthedge.com/connector/schema/basetypes}HealthRulesResourceType"&gt;
 *       &lt;group ref="{http://www.healthedge.com/connector/schema/cobpolicy}COBPolicyGroup"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COBPolicyType", namespace = "http://www.healthedge.com/connector/schema/cobpolicy", propOrder = {
    "cobPolicyIdentifier",
    "cobPolicyId",
    "leadSourceForOtherInsuranceCode",
    "relationshipToSubscriberDefinitionReference",
    "otherInsuranceCompanyName",
    "policyType",
    "policyHolderName",
    "benefitPlanName",
    "groupNumber",
    "memberId",
    "benefitPlanTypeCode",
    "dateRanges",
    "subscriberIdList",
    "subscriberName",
    "subscriberDOB",
    "subscriberGender",
    "rxInfo",
    "correspondenceInfo",
    "carrierIds",
    "serviceCategoryList"
})
public class COBPolicyType
    extends HealthRulesResourceType
{

    protected Integer cobPolicyIdentifier;
    protected String cobPolicyId;
    protected CodeEntryInputType leadSourceForOtherInsuranceCode;
    protected ReferenceType relationshipToSubscriberDefinitionReference;
    protected String otherInsuranceCompanyName;
    protected String policyType;
    protected String policyHolderName;
    protected String benefitPlanName;
    protected String groupNumber;
    protected String memberId;
    protected CodeEntryInputType benefitPlanTypeCode;
    @XmlElement(required = true)
    protected List<COBPolicyDateRangeType> dateRanges;
    protected List<IdentificationNumberType> subscriberIdList;
    protected PersonNameType subscriberName;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar subscriberDOB;
    @XmlSchemaType(name = "string")
    protected GenderCodeType subscriberGender;
    protected RxInfoType rxInfo;
    protected CorrespondenceInformationType correspondenceInfo;
    protected List<IdentificationNumberType> carrierIds;
    protected ServiceCategoryList serviceCategoryList;

    /**
     * Gets the value of the cobPolicyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCobPolicyIdentifier() {
        return cobPolicyIdentifier;
    }

    /**
     * Sets the value of the cobPolicyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCobPolicyIdentifier(Integer value) {
        this.cobPolicyIdentifier = value;
    }

    /**
     * Gets the value of the cobPolicyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCobPolicyId() {
        return cobPolicyId;
    }

    /**
     * Sets the value of the cobPolicyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCobPolicyId(String value) {
        this.cobPolicyId = value;
    }

    /**
     * Gets the value of the leadSourceForOtherInsuranceCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeEntryInputType }
     *     
     */
    public CodeEntryInputType getLeadSourceForOtherInsuranceCode() {
        return leadSourceForOtherInsuranceCode;
    }

    /**
     * Sets the value of the leadSourceForOtherInsuranceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeEntryInputType }
     *     
     */
    public void setLeadSourceForOtherInsuranceCode(CodeEntryInputType value) {
        this.leadSourceForOtherInsuranceCode = value;
    }

    /**
     * Gets the value of the relationshipToSubscriberDefinitionReference property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getRelationshipToSubscriberDefinitionReference() {
        return relationshipToSubscriberDefinitionReference;
    }

    /**
     * Sets the value of the relationshipToSubscriberDefinitionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setRelationshipToSubscriberDefinitionReference(ReferenceType value) {
        this.relationshipToSubscriberDefinitionReference = value;
    }

    /**
     * Gets the value of the otherInsuranceCompanyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherInsuranceCompanyName() {
        return otherInsuranceCompanyName;
    }

    /**
     * Sets the value of the otherInsuranceCompanyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherInsuranceCompanyName(String value) {
        this.otherInsuranceCompanyName = value;
    }

    /**
     * Gets the value of the policyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyType() {
        return policyType;
    }

    /**
     * Sets the value of the policyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyType(String value) {
        this.policyType = value;
    }

    /**
     * Gets the value of the policyHolderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyHolderName() {
        return policyHolderName;
    }

    /**
     * Sets the value of the policyHolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyHolderName(String value) {
        this.policyHolderName = value;
    }

    /**
     * Gets the value of the benefitPlanName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitPlanName() {
        return benefitPlanName;
    }

    /**
     * Sets the value of the benefitPlanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitPlanName(String value) {
        this.benefitPlanName = value;
    }

    /**
     * Gets the value of the groupNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupNumber() {
        return groupNumber;
    }

    /**
     * Sets the value of the groupNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupNumber(String value) {
        this.groupNumber = value;
    }

    /**
     * Gets the value of the memberId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * Sets the value of the memberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberId(String value) {
        this.memberId = value;
    }

    /**
     * Gets the value of the benefitPlanTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeEntryInputType }
     *     
     */
    public CodeEntryInputType getBenefitPlanTypeCode() {
        return benefitPlanTypeCode;
    }

    /**
     * Sets the value of the benefitPlanTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeEntryInputType }
     *     
     */
    public void setBenefitPlanTypeCode(CodeEntryInputType value) {
        this.benefitPlanTypeCode = value;
    }

    /**
     * Gets the value of the dateRanges property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateRanges property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateRanges().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COBPolicyDateRangeType }
     * 
     * 
     */
    public List<COBPolicyDateRangeType> getDateRanges() {
        if (dateRanges == null) {
            dateRanges = new ArrayList<COBPolicyDateRangeType>();
        }
        return this.dateRanges;
    }

    /**
     * Gets the value of the subscriberIdList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscriberIdList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscriberIdList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationNumberType }
     * 
     * 
     */
    public List<IdentificationNumberType> getSubscriberIdList() {
        if (subscriberIdList == null) {
            subscriberIdList = new ArrayList<IdentificationNumberType>();
        }
        return this.subscriberIdList;
    }

    /**
     * Gets the value of the subscriberName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameType }
     *     
     */
    public PersonNameType getSubscriberName() {
        return subscriberName;
    }

    /**
     * Sets the value of the subscriberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameType }
     *     
     */
    public void setSubscriberName(PersonNameType value) {
        this.subscriberName = value;
    }

    /**
     * Gets the value of the subscriberDOB property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubscriberDOB() {
        return subscriberDOB;
    }

    /**
     * Sets the value of the subscriberDOB property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubscriberDOB(XMLGregorianCalendar value) {
        this.subscriberDOB = value;
    }

    /**
     * Gets the value of the subscriberGender property.
     * 
     * @return
     *     possible object is
     *     {@link GenderCodeType }
     *     
     */
    public GenderCodeType getSubscriberGender() {
        return subscriberGender;
    }

    /**
     * Sets the value of the subscriberGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderCodeType }
     *     
     */
    public void setSubscriberGender(GenderCodeType value) {
        this.subscriberGender = value;
    }

    /**
     * Gets the value of the rxInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RxInfoType }
     *     
     */
    public RxInfoType getRxInfo() {
        return rxInfo;
    }

    /**
     * Sets the value of the rxInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RxInfoType }
     *     
     */
    public void setRxInfo(RxInfoType value) {
        this.rxInfo = value;
    }

    /**
     * Gets the value of the correspondenceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CorrespondenceInformationType }
     *     
     */
    public CorrespondenceInformationType getCorrespondenceInfo() {
        return correspondenceInfo;
    }

    /**
     * Sets the value of the correspondenceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrespondenceInformationType }
     *     
     */
    public void setCorrespondenceInfo(CorrespondenceInformationType value) {
        this.correspondenceInfo = value;
    }

    /**
     * Gets the value of the carrierIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the carrierIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCarrierIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationNumberType }
     * 
     * 
     */
    public List<IdentificationNumberType> getCarrierIds() {
        if (carrierIds == null) {
            carrierIds = new ArrayList<IdentificationNumberType>();
        }
        return this.carrierIds;
    }

    /**
     * Gets the value of the serviceCategoryList property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCategoryList }
     *     
     */
    public ServiceCategoryList getServiceCategoryList() {
        return serviceCategoryList;
    }

    /**
     * Sets the value of the serviceCategoryList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCategoryList }
     *     
     */
    public void setServiceCategoryList(ServiceCategoryList value) {
        this.serviceCategoryList = value;
    }

}
