//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for COBPolicyListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="COBPolicyListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="memberHccID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cobPolicy" type="{http://www.healthedge.com/connector/schema/cobpolicy}COBPolicyType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COBPolicyListType", namespace = "http://www.healthedge.com/connector/schema/cobpolicy", propOrder = {
    "memberHccID",
    "cobPolicy"
})
public class COBPolicyListType {

    @XmlElement(required = true)
    protected String memberHccID;
    @XmlElement(required = true)
    protected List<COBPolicyType> cobPolicy;

    /**
     * Gets the value of the memberHccID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberHccID() {
        return memberHccID;
    }

    /**
     * Sets the value of the memberHccID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberHccID(String value) {
        this.memberHccID = value;
    }

    /**
     * Gets the value of the cobPolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cobPolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCobPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COBPolicyType }
     * 
     * 
     */
    public List<COBPolicyType> getCobPolicy() {
        if (cobPolicy == null) {
            cobPolicy = new ArrayList<COBPolicyType>();
        }
        return this.cobPolicy;
    }

}
