//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CorrespondenceSubjectInputType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="CorrespondenceSubjectInputType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Bill"/&gt;
 *     &lt;enumeration value="Claim"/&gt;
 *     &lt;enumeration value="Payment"/&gt;
 *     &lt;enumeration value="Member"/&gt;
 *     &lt;enumeration value="Authorization"/&gt;
 *     &lt;enumeration value="BenefitPlan"/&gt;
 *     &lt;enumeration value="Not Applicable"/&gt;
 *     &lt;enumeration value="COB Policy"/&gt;
 *     &lt;enumeration value="Funding Request"/&gt;
 *     &lt;enumeration value="EMPTY_VALUE_INDICATED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CorrespondenceSubjectInputType")
@XmlEnum
public enum CorrespondenceSubjectInputType {

    @XmlEnumValue("Bill")
    BILL("Bill"),
    @XmlEnumValue("Claim")
    CLAIM("Claim"),
    @XmlEnumValue("Payment")
    PAYMENT("Payment"),
    @XmlEnumValue("Member")
    MEMBER("Member"),
    @XmlEnumValue("Authorization")
    AUTHORIZATION("Authorization"),
    @XmlEnumValue("BenefitPlan")
    BENEFIT_PLAN("BenefitPlan"),
    @XmlEnumValue("Not Applicable")
    NOT_APPLICABLE("Not Applicable"),
    @XmlEnumValue("COB Policy")
    COB_POLICY("COB Policy"),
    @XmlEnumValue("Funding Request")
    FUNDING_REQUEST("Funding Request"),
    EMPTY_VALUE_INDICATED("EMPTY_VALUE_INDICATED");
    private final String value;

    CorrespondenceSubjectInputType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CorrespondenceSubjectInputType fromValue(String v) {
        for (CorrespondenceSubjectInputType c: CorrespondenceSubjectInputType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
