//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CorrespondenceInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CorrespondenceInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="emailAddress" type="{http://www.healthedge.com/connector/schema/basetypes}EmailAddressValueType" minOccurs="0"/&gt;
 *         &lt;element name="addressInformation" type="{http://www.healthedge.com/connector/schema/basetypes}CorrespondenceAddressInformationType" minOccurs="0"/&gt;
 *         &lt;element name="contacts" type="{http://www.healthedge.com/connector/schema/basetypes}ContactListType" minOccurs="0"/&gt;
 *         &lt;element name="correspondenceUsageTypeCode" type="{http://www.healthedge.com/connector/schema/basetypes}CodeEntryInputType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorrespondenceInfoType", propOrder = {
    "emailAddress",
    "addressInformation",
    "contacts",
    "correspondenceUsageTypeCode"
})
public class CorrespondenceInfoType {

    protected String emailAddress;
    protected CorrespondenceAddressInformationType addressInformation;
    protected ContactListType contacts;
    protected CodeEntryInputType correspondenceUsageTypeCode;

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the addressInformation property.
     * 
     * @return
     *     possible object is
     *     {@link CorrespondenceAddressInformationType }
     *     
     */
    public CorrespondenceAddressInformationType getAddressInformation() {
        return addressInformation;
    }

    /**
     * Sets the value of the addressInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrespondenceAddressInformationType }
     *     
     */
    public void setAddressInformation(CorrespondenceAddressInformationType value) {
        this.addressInformation = value;
    }

    /**
     * Gets the value of the contacts property.
     * 
     * @return
     *     possible object is
     *     {@link ContactListType }
     *     
     */
    public ContactListType getContacts() {
        return contacts;
    }

    /**
     * Sets the value of the contacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactListType }
     *     
     */
    public void setContacts(ContactListType value) {
        this.contacts = value;
    }

    /**
     * Gets the value of the correspondenceUsageTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeEntryInputType }
     *     
     */
    public CodeEntryInputType getCorrespondenceUsageTypeCode() {
        return correspondenceUsageTypeCode;
    }

    /**
     * Sets the value of the correspondenceUsageTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeEntryInputType }
     *     
     */
    public void setCorrespondenceUsageTypeCode(CodeEntryInputType value) {
        this.correspondenceUsageTypeCode = value;
    }

}
