//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisabilityTypeDomainType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="DisabilityTypeDomainType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Awaiting Verification"/&gt;
 *     &lt;enumeration value="No Verification Received"/&gt;
 *     &lt;enumeration value="Verification Under Review"/&gt;
 *     &lt;enumeration value="Indefinitely Approved"/&gt;
 *     &lt;enumeration value="Temporarily Approved"/&gt;
 *     &lt;enumeration value="Awaiting Re-verification"/&gt;
 *     &lt;enumeration value="Denied"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DisabilityTypeDomainType")
@XmlEnum
public enum DisabilityTypeDomainType {

    @XmlEnumValue("Awaiting Verification")
    AWAITING_VERIFICATION("Awaiting Verification"),
    @XmlEnumValue("No Verification Received")
    NO_VERIFICATION_RECEIVED("No Verification Received"),
    @XmlEnumValue("Verification Under Review")
    VERIFICATION_UNDER_REVIEW("Verification Under Review"),
    @XmlEnumValue("Indefinitely Approved")
    INDEFINITELY_APPROVED("Indefinitely Approved"),
    @XmlEnumValue("Temporarily Approved")
    TEMPORARILY_APPROVED("Temporarily Approved"),
    @XmlEnumValue("Awaiting Re-verification")
    AWAITING_RE_VERIFICATION("Awaiting Re-verification"),
    @XmlEnumValue("Denied")
    DENIED("Denied");
    private final String value;

    DisabilityTypeDomainType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DisabilityTypeDomainType fromValue(String v) {
        for (DisabilityTypeDomainType c: DisabilityTypeDomainType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
