//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EnrollmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnrollmentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.healthedge.com/connector/schema/basetypes}HealthRulesResourceType"&gt;
 *       &lt;group ref="{http://www.healthedge.com/connector/schema/enrollmentsparse}EnrollmentGroup"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnrollmentType", namespace = "http://www.healthedge.com/connector/schema/enrollmentsparse", propOrder = {
    "transactionId",
    "actionMode",
    "asOfDate",
    "activate",
    "subscriberId",
    "cascadeTerms",
    "cascadeCancels",
    "cascadeReinstate",
    "sendToWorkBasketIfExceptionsPresent",
    "requestFromHmem",
    "subscription",
    "member",
    "udtResultQuery"
})
public class EnrollmentType
    extends HealthRulesResourceType
{

    protected String transactionId;
    @XmlElement(defaultValue = "SPARSE")
    @XmlSchemaType(name = "string")
    protected ActionModeType actionMode;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar asOfDate;
    protected Boolean activate;
    protected String subscriberId;
    @XmlElement(defaultValue = "true")
    protected Boolean cascadeTerms;
    @XmlElement(defaultValue = "true")
    protected Boolean cascadeCancels;
    @XmlElement(defaultValue = "false")
    protected Boolean cascadeReinstate;
    @XmlElement(defaultValue = "true")
    protected Boolean sendToWorkBasketIfExceptionsPresent;
    @XmlElement(defaultValue = "false")
    protected Boolean requestFromHmem;
    protected SubscriptionType subscription;
    @XmlElement(required = true)
    protected List<MembershipType> member;
    protected List<UdtAttributes> udtResultQuery;

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the actionMode property.
     * 
     * @return
     *     possible object is
     *     {@link ActionModeType }
     *     
     */
    public ActionModeType getActionMode() {
        return actionMode;
    }

    /**
     * Sets the value of the actionMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionModeType }
     *     
     */
    public void setActionMode(ActionModeType value) {
        this.actionMode = value;
    }

    /**
     * Gets the value of the asOfDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAsOfDate() {
        return asOfDate;
    }

    /**
     * Sets the value of the asOfDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAsOfDate(XMLGregorianCalendar value) {
        this.asOfDate = value;
    }

    /**
     * Gets the value of the activate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActivate() {
        return activate;
    }

    /**
     * Sets the value of the activate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActivate(Boolean value) {
        this.activate = value;
    }

    /**
     * Gets the value of the subscriberId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberId() {
        return subscriberId;
    }

    /**
     * Sets the value of the subscriberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberId(String value) {
        this.subscriberId = value;
    }

    /**
     * Gets the value of the cascadeTerms property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCascadeTerms() {
        return cascadeTerms;
    }

    /**
     * Sets the value of the cascadeTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCascadeTerms(Boolean value) {
        this.cascadeTerms = value;
    }

    /**
     * Gets the value of the cascadeCancels property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCascadeCancels() {
        return cascadeCancels;
    }

    /**
     * Sets the value of the cascadeCancels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCascadeCancels(Boolean value) {
        this.cascadeCancels = value;
    }

    /**
     * Gets the value of the cascadeReinstate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCascadeReinstate() {
        return cascadeReinstate;
    }

    /**
     * Sets the value of the cascadeReinstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCascadeReinstate(Boolean value) {
        this.cascadeReinstate = value;
    }

    /**
     * Gets the value of the sendToWorkBasketIfExceptionsPresent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSendToWorkBasketIfExceptionsPresent() {
        return sendToWorkBasketIfExceptionsPresent;
    }

    /**
     * Sets the value of the sendToWorkBasketIfExceptionsPresent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSendToWorkBasketIfExceptionsPresent(Boolean value) {
        this.sendToWorkBasketIfExceptionsPresent = value;
    }

    /**
     * Gets the value of the requestFromHmem property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestFromHmem() {
        return requestFromHmem;
    }

    /**
     * Sets the value of the requestFromHmem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestFromHmem(Boolean value) {
        this.requestFromHmem = value;
    }

    /**
     * Gets the value of the subscription property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionType }
     *     
     */
    public SubscriptionType getSubscription() {
        return subscription;
    }

    /**
     * Sets the value of the subscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionType }
     *     
     */
    public void setSubscription(SubscriptionType value) {
        this.subscription = value;
    }

    /**
     * Gets the value of the member property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the member property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMember().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MembershipType }
     * 
     * 
     */
    public List<MembershipType> getMember() {
        if (member == null) {
            member = new ArrayList<MembershipType>();
        }
        return this.member;
    }

    /**
     * Gets the value of the udtResultQuery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the udtResultQuery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUdtResultQuery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UdtAttributes }
     * 
     * 
     */
    public List<UdtAttributes> getUdtResultQuery() {
        if (udtResultQuery == null) {
            udtResultQuery = new ArrayList<UdtAttributes>();
        }
        return this.udtResultQuery;
    }

}
