//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EthnicityCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EthnicityCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Not Provided"/&gt;
 *     &lt;enumeration value="Not Applicable"/&gt;
 *     &lt;enumeration value="Asian or Pacific Islander"/&gt;
 *     &lt;enumeration value="Black"/&gt;
 *     &lt;enumeration value="Caucasian"/&gt;
 *     &lt;enumeration value="Subcontinent Asian American"/&gt;
 *     &lt;enumeration value="Other Race or Ethnicity"/&gt;
 *     &lt;enumeration value="Asian Pacific American"/&gt;
 *     &lt;enumeration value="Native American"/&gt;
 *     &lt;enumeration value="Hispanic"/&gt;
 *     &lt;enumeration value="American Indian or Alaskan Native"/&gt;
 *     &lt;enumeration value="Native Hawaiian"/&gt;
 *     &lt;enumeration value="Black (Non-Hispanic)"/&gt;
 *     &lt;enumeration value="White (Non-Hispanic)"/&gt;
 *     &lt;enumeration value="Pacific Islander"/&gt;
 *     &lt;enumeration value="Mutually Defined"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EthnicityCodeType")
@XmlEnum
public enum EthnicityCodeType {

    @XmlEnumValue("Not Provided")
    NOT_PROVIDED("Not Provided"),
    @XmlEnumValue("Not Applicable")
    NOT_APPLICABLE("Not Applicable"),
    @XmlEnumValue("Asian or Pacific Islander")
    ASIAN_OR_PACIFIC_ISLANDER("Asian or Pacific Islander"),
    @XmlEnumValue("Black")
    BLACK("Black"),
    @XmlEnumValue("Caucasian")
    CAUCASIAN("Caucasian"),
    @XmlEnumValue("Subcontinent Asian American")
    SUBCONTINENT_ASIAN_AMERICAN("Subcontinent Asian American"),
    @XmlEnumValue("Other Race or Ethnicity")
    OTHER_RACE_OR_ETHNICITY("Other Race or Ethnicity"),
    @XmlEnumValue("Asian Pacific American")
    ASIAN_PACIFIC_AMERICAN("Asian Pacific American"),
    @XmlEnumValue("Native American")
    NATIVE_AMERICAN("Native American"),
    @XmlEnumValue("Hispanic")
    HISPANIC("Hispanic"),
    @XmlEnumValue("American Indian or Alaskan Native")
    AMERICAN_INDIAN_OR_ALASKAN_NATIVE("American Indian or Alaskan Native"),
    @XmlEnumValue("Native Hawaiian")
    NATIVE_HAWAIIAN("Native Hawaiian"),
    @XmlEnumValue("Black (Non-Hispanic)")
    BLACK_NON_HISPANIC("Black (Non-Hispanic)"),
    @XmlEnumValue("White (Non-Hispanic)")
    WHITE_NON_HISPANIC("White (Non-Hispanic)"),
    @XmlEnumValue("Pacific Islander")
    PACIFIC_ISLANDER("Pacific Islander"),
    @XmlEnumValue("Mutually Defined")
    MUTUALLY_DEFINED("Mutually Defined");
    private final String value;

    EthnicityCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EthnicityCodeType fromValue(String v) {
        for (EthnicityCodeType c: EthnicityCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
