//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InsuranceCompanyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuranceCompanyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.healthedge.com/connector/schema/basetypes}InsuranceCompanyGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuranceCompanyType", propOrder = {
    "companyName",
    "specialRoutingInformation",
    "address"
})
public class InsuranceCompanyType {

    protected String companyName;
    protected String specialRoutingInformation;
    protected InsuranceCompanyType.Address address;

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the specialRoutingInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialRoutingInformation() {
        return specialRoutingInformation;
    }

    /**
     * Sets the value of the specialRoutingInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialRoutingInformation(String value) {
        this.specialRoutingInformation = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceCompanyType.Address }
     *     
     */
    public InsuranceCompanyType.Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceCompanyType.Address }
     *     
     */
    public void setAddress(InsuranceCompanyType.Address value) {
        this.address = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="postalAddress" type="{http://www.healthedge.com/connector/schema/basetypes}PostalAddressType" minOccurs="0"/&gt;
     *         &lt;element name="addressPhoneList" type="{http://www.healthedge.com/connector/schema/basetypes}TelephoneNumberListType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "postalAddress",
        "addressPhoneList"
    })
    public static class Address {

        protected PostalAddressType postalAddress;
        protected TelephoneNumberListType addressPhoneList;

        /**
         * Gets the value of the postalAddress property.
         * 
         * @return
         *     possible object is
         *     {@link PostalAddressType }
         *     
         */
        public PostalAddressType getPostalAddress() {
            return postalAddress;
        }

        /**
         * Sets the value of the postalAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link PostalAddressType }
         *     
         */
        public void setPostalAddress(PostalAddressType value) {
            this.postalAddress = value;
        }

        /**
         * Gets the value of the addressPhoneList property.
         * 
         * @return
         *     possible object is
         *     {@link TelephoneNumberListType }
         *     
         */
        public TelephoneNumberListType getAddressPhoneList() {
            return addressPhoneList;
        }

        /**
         * Sets the value of the addressPhoneList property.
         * 
         * @param value
         *     allowed object is
         *     {@link TelephoneNumberListType }
         *     
         */
        public void setAddressPhoneList(TelephoneNumberListType value) {
            this.addressPhoneList = value;
        }

    }

}
