//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MemberDentalInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemberDentalInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.healthedge.com/connector/schema/basetypes}MemberDentalInfoGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemberDentalInfoType", propOrder = {
    "remarks",
    "missingTeeth"
})
public class MemberDentalInfoType {

    protected String remarks;
    protected MemberDentalInfoType.MissingTeeth missingTeeth;

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the missingTeeth property.
     * 
     * @return
     *     possible object is
     *     {@link MemberDentalInfoType.MissingTeeth }
     *     
     */
    public MemberDentalInfoType.MissingTeeth getMissingTeeth() {
        return missingTeeth;
    }

    /**
     * Sets the value of the missingTeeth property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberDentalInfoType.MissingTeeth }
     *     
     */
    public void setMissingTeeth(MemberDentalInfoType.MissingTeeth value) {
        this.missingTeeth = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="listMode" type="{http://www.healthedge.com/connector/schema/basetypes}ListActionType" minOccurs="0"/&gt;
     *         &lt;element name="toothName" type="{http://www.healthedge.com/connector/schema/basetypes}ToothNameDomainType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listMode",
        "toothName"
    })
    public static class MissingTeeth {

        @XmlSchemaType(name = "string")
        protected ListActionType listMode;
        protected List<String> toothName;

        /**
         * Gets the value of the listMode property.
         * 
         * @return
         *     possible object is
         *     {@link ListActionType }
         *     
         */
        public ListActionType getListMode() {
            return listMode;
        }

        /**
         * Sets the value of the listMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link ListActionType }
         *     
         */
        public void setListMode(ListActionType value) {
            this.listMode = value;
        }

        /**
         * Gets the value of the toothName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the toothName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getToothName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getToothName() {
            if (toothName == null) {
                toothName = new ArrayList<String>();
            }
            return this.toothName;
        }

    }

}
