//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MembershipProviderSelectionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MembershipProviderSelectionsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.healthedge.com/connector/schema/enrollmenttypes}MembershipProviderSelectionsGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MembershipProviderSelectionsType", namespace = "http://www.healthedge.com/connector/schema/enrollmenttypes", propOrder = {
    "providerRoleName",
    "dataRanges"
})
public class MembershipProviderSelectionsType {

    @XmlElement(name = "ProviderRoleName")
    protected List<String> providerRoleName;
    protected List<MembershipInactiveDateRangesType> dataRanges;

    /**
     * Gets the value of the providerRoleName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the providerRoleName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProviderRoleName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProviderRoleName() {
        if (providerRoleName == null) {
            providerRoleName = new ArrayList<String>();
        }
        return this.providerRoleName;
    }

    /**
     * Gets the value of the dataRanges property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataRanges property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataRanges().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MembershipInactiveDateRangesType }
     * 
     * 
     */
    public List<MembershipInactiveDateRangesType> getDataRanges() {
        if (dataRanges == null) {
            dataRanges = new ArrayList<MembershipInactiveDateRangesType>();
        }
        return this.dataRanges;
    }

}
