//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MemberComplianceProgramResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemberComplianceProgramResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="memberComplianceProgramInput" type="{http://www.healthedge.com/connector/schema/membercomplianceprogram}MembershipComplianceProgramSelectionListType"/&gt;
 *         &lt;element name="status" type="{http://www.healthedge.com/connector/schema/basetypes}ServiceStatusType" minOccurs="0"/&gt;
 *         &lt;element name="transactionInformation" type="{http://www.healthedge.com/connector/schema/basetypes}TransactionInformationType" minOccurs="0"/&gt;
 *         &lt;element name="errors" type="{http://www.healthedge.com/connector/schema/basetypes}ErrorsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemberComplianceProgramResponseType", namespace = "http://www.healthedge.com/connector/schema/membercomplianceprogram", propOrder = {
    "memberComplianceProgramInput",
    "status",
    "transactionInformation",
    "errors"
})
public class MemberComplianceProgramResponseType {

    @XmlElement(required = true)
    protected MembershipComplianceProgramSelectionListType memberComplianceProgramInput;
    @XmlSchemaType(name = "string")
    protected ServiceStatusType status;
    protected TransactionInformationType transactionInformation;
    protected ErrorsType errors;

    /**
     * Gets the value of the memberComplianceProgramInput property.
     * 
     * @return
     *     possible object is
     *     {@link MembershipComplianceProgramSelectionListType }
     *     
     */
    public MembershipComplianceProgramSelectionListType getMemberComplianceProgramInput() {
        return memberComplianceProgramInput;
    }

    /**
     * Sets the value of the memberComplianceProgramInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link MembershipComplianceProgramSelectionListType }
     *     
     */
    public void setMemberComplianceProgramInput(MembershipComplianceProgramSelectionListType value) {
        this.memberComplianceProgramInput = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceStatusType }
     *     
     */
    public ServiceStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceStatusType }
     *     
     */
    public void setStatus(ServiceStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the transactionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionInformationType }
     *     
     */
    public TransactionInformationType getTransactionInformation() {
        return transactionInformation;
    }

    /**
     * Sets the value of the transactionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionInformationType }
     *     
     */
    public void setTransactionInformation(TransactionInformationType value) {
        this.transactionInformation = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorsType }
     *     
     */
    public ErrorsType getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorsType }
     *     
     */
    public void setErrors(ErrorsType value) {
        this.errors = value;
    }

}
