//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MemberResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemberResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="memberId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="maintenanceOverride" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="maintenanceOverrideResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="endorsementDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.healthedge.com/connector/schema/basetypes}ServiceStatusType" minOccurs="0"/&gt;
 *         &lt;element name="planSelection" type="{http://www.healthedge.com/connector/schema/enrollmentsparseresponse}PlanSelectionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="providerSelection" type="{http://www.healthedge.com/connector/schema/enrollmentsparseresponse}ProviderSelectionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="transactionInformation" type="{http://www.healthedge.com/connector/schema/basetypes}TransactionInformationType" minOccurs="0"/&gt;
 *         &lt;element name="secondaryTransactionInformation" type="{http://www.healthedge.com/connector/schema/basetypes}TransactionInformationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="individualMappingInfo" type="{http://www.healthedge.com/connector/schema/enrollmentsparseresponse}IndividualMappingInfo" minOccurs="0"/&gt;
 *         &lt;element name="memberInputID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="manualReviewList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="listMode" type="{http://www.healthedge.com/connector/schema/basetypes}ListActionType" minOccurs="0"/&gt;
 *                   &lt;element name="manualReview" type="{http://www.healthedge.com/connector/schema/enrollmenttypes}MemberManualReviewType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemberResponseType", namespace = "http://www.healthedge.com/connector/schema/enrollmentsparseresponse", propOrder = {
    "memberId",
    "maintenanceOverride",
    "maintenanceOverrideResult",
    "lastName",
    "firstName",
    "dob",
    "endorsementDate",
    "status",
    "planSelection",
    "providerSelection",
    "transactionInformation",
    "secondaryTransactionInformation",
    "individualMappingInfo",
    "memberInputID",
    "manualReviewList"
})
public class MemberResponseType {

    protected String memberId;
    @XmlElement(defaultValue = "true")
    protected Boolean maintenanceOverride;
    protected String maintenanceOverrideResult;
    protected String lastName;
    protected String firstName;
    protected String dob;
    protected String endorsementDate;
    @XmlSchemaType(name = "string")
    protected ServiceStatusType status;
    protected List<PlanSelectionType> planSelection;
    protected List<ProviderSelectionType2> providerSelection;
    protected TransactionInformationType transactionInformation;
    protected List<TransactionInformationType> secondaryTransactionInformation;
    protected IndividualMappingInfo individualMappingInfo;
    protected String memberInputID;
    protected MemberResponseType.ManualReviewList manualReviewList;

    /**
     * Gets the value of the memberId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * Sets the value of the memberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberId(String value) {
        this.memberId = value;
    }

    /**
     * Gets the value of the maintenanceOverride property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMaintenanceOverride() {
        return maintenanceOverride;
    }

    /**
     * Sets the value of the maintenanceOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMaintenanceOverride(Boolean value) {
        this.maintenanceOverride = value;
    }

    /**
     * Gets the value of the maintenanceOverrideResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaintenanceOverrideResult() {
        return maintenanceOverrideResult;
    }

    /**
     * Sets the value of the maintenanceOverrideResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaintenanceOverrideResult(String value) {
        this.maintenanceOverrideResult = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDob() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDob(String value) {
        this.dob = value;
    }

    /**
     * Gets the value of the endorsementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndorsementDate() {
        return endorsementDate;
    }

    /**
     * Sets the value of the endorsementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndorsementDate(String value) {
        this.endorsementDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceStatusType }
     *     
     */
    public ServiceStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceStatusType }
     *     
     */
    public void setStatus(ServiceStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the planSelection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the planSelection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlanSelection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlanSelectionType }
     * 
     * 
     */
    public List<PlanSelectionType> getPlanSelection() {
        if (planSelection == null) {
            planSelection = new ArrayList<PlanSelectionType>();
        }
        return this.planSelection;
    }

    /**
     * Gets the value of the providerSelection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the providerSelection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProviderSelection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProviderSelectionType2 }
     * 
     * 
     */
    public List<ProviderSelectionType2> getProviderSelection() {
        if (providerSelection == null) {
            providerSelection = new ArrayList<ProviderSelectionType2>();
        }
        return this.providerSelection;
    }

    /**
     * Gets the value of the transactionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionInformationType }
     *     
     */
    public TransactionInformationType getTransactionInformation() {
        return transactionInformation;
    }

    /**
     * Sets the value of the transactionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionInformationType }
     *     
     */
    public void setTransactionInformation(TransactionInformationType value) {
        this.transactionInformation = value;
    }

    /**
     * Gets the value of the secondaryTransactionInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secondaryTransactionInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecondaryTransactionInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionInformationType }
     * 
     * 
     */
    public List<TransactionInformationType> getSecondaryTransactionInformation() {
        if (secondaryTransactionInformation == null) {
            secondaryTransactionInformation = new ArrayList<TransactionInformationType>();
        }
        return this.secondaryTransactionInformation;
    }

    /**
     * Gets the value of the individualMappingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualMappingInfo }
     *     
     */
    public IndividualMappingInfo getIndividualMappingInfo() {
        return individualMappingInfo;
    }

    /**
     * Sets the value of the individualMappingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualMappingInfo }
     *     
     */
    public void setIndividualMappingInfo(IndividualMappingInfo value) {
        this.individualMappingInfo = value;
    }

    /**
     * Gets the value of the memberInputID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberInputID() {
        return memberInputID;
    }

    /**
     * Sets the value of the memberInputID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberInputID(String value) {
        this.memberInputID = value;
    }

    /**
     * Gets the value of the manualReviewList property.
     * 
     * @return
     *     possible object is
     *     {@link MemberResponseType.ManualReviewList }
     *     
     */
    public MemberResponseType.ManualReviewList getManualReviewList() {
        return manualReviewList;
    }

    /**
     * Sets the value of the manualReviewList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberResponseType.ManualReviewList }
     *     
     */
    public void setManualReviewList(MemberResponseType.ManualReviewList value) {
        this.manualReviewList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="listMode" type="{http://www.healthedge.com/connector/schema/basetypes}ListActionType" minOccurs="0"/&gt;
     *         &lt;element name="manualReview" type="{http://www.healthedge.com/connector/schema/enrollmenttypes}MemberManualReviewType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listMode",
        "manualReview"
    })
    public static class ManualReviewList {

        @XmlSchemaType(name = "string")
        protected ListActionType listMode;
        protected List<MemberManualReviewType> manualReview;

        /**
         * Gets the value of the listMode property.
         * 
         * @return
         *     possible object is
         *     {@link ListActionType }
         *     
         */
        public ListActionType getListMode() {
            return listMode;
        }

        /**
         * Sets the value of the listMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link ListActionType }
         *     
         */
        public void setListMode(ListActionType value) {
            this.listMode = value;
        }

        /**
         * Gets the value of the manualReview property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the manualReview property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getManualReview().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MemberManualReviewType }
         * 
         * 
         */
        public List<MemberManualReviewType> getManualReview() {
            if (manualReview == null) {
                manualReview = new ArrayList<MemberManualReviewType>();
            }
            return this.manualReview;
        }

    }

}
