//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PayeeBankAccountsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayeeBankAccountsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.healthedge.com/connector/schema/basetypes}HealthRulesResourceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.healthedge.com/connector/schema/payeebankaccounts}PayeeBankAccountsGroup"/&gt;
 *         &lt;element name="maintenanceComment" type="{http://www.healthedge.com/connector/schema/basetypes}String900Type" minOccurs="0"/&gt;
 *         &lt;element name="maintenanceReasonCode" type="{http://www.healthedge.com/connector/schema/basetypes}CodeEntryInputType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayeeBankAccountsType", namespace = "http://www.healthedge.com/connector/schema/payeebankaccounts", propOrder = {
    "instanceActiveCode",
    "bankAccountId",
    "oldBankAccountId",
    "endorsementEffectiveDate",
    "endorsementExpirationDate",
    "payee",
    "payeeBankAccountDateRange",
    "payeeBankAccountDateRanges",
    "maintenanceComment",
    "maintenanceReasonCode"
})
public class PayeeBankAccountsType
    extends HealthRulesResourceType
{

    protected String instanceActiveCode;
    @XmlElement(required = true)
    protected String bankAccountId;
    protected String oldBankAccountId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endorsementEffectiveDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endorsementExpirationDate;
    protected PayeeType payee;
    protected PayeeBankAccountDateRangeType payeeBankAccountDateRange;
    protected PayeeBankAccountsType.PayeeBankAccountDateRanges payeeBankAccountDateRanges;
    protected String maintenanceComment;
    protected CodeEntryInputType maintenanceReasonCode;

    /**
     * Gets the value of the instanceActiveCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceActiveCode() {
        return instanceActiveCode;
    }

    /**
     * Sets the value of the instanceActiveCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceActiveCode(String value) {
        this.instanceActiveCode = value;
    }

    /**
     * Gets the value of the bankAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankAccountId() {
        return bankAccountId;
    }

    /**
     * Sets the value of the bankAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankAccountId(String value) {
        this.bankAccountId = value;
    }

    /**
     * Gets the value of the oldBankAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldBankAccountId() {
        return oldBankAccountId;
    }

    /**
     * Sets the value of the oldBankAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldBankAccountId(String value) {
        this.oldBankAccountId = value;
    }

    /**
     * Gets the value of the endorsementEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndorsementEffectiveDate() {
        return endorsementEffectiveDate;
    }

    /**
     * Sets the value of the endorsementEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndorsementEffectiveDate(XMLGregorianCalendar value) {
        this.endorsementEffectiveDate = value;
    }

    /**
     * Gets the value of the endorsementExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndorsementExpirationDate() {
        return endorsementExpirationDate;
    }

    /**
     * Sets the value of the endorsementExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndorsementExpirationDate(XMLGregorianCalendar value) {
        this.endorsementExpirationDate = value;
    }

    /**
     * Gets the value of the payee property.
     * 
     * @return
     *     possible object is
     *     {@link PayeeType }
     *     
     */
    public PayeeType getPayee() {
        return payee;
    }

    /**
     * Sets the value of the payee property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayeeType }
     *     
     */
    public void setPayee(PayeeType value) {
        this.payee = value;
    }

    /**
     * Gets the value of the payeeBankAccountDateRange property.
     * 
     * @return
     *     possible object is
     *     {@link PayeeBankAccountDateRangeType }
     *     
     */
    public PayeeBankAccountDateRangeType getPayeeBankAccountDateRange() {
        return payeeBankAccountDateRange;
    }

    /**
     * Sets the value of the payeeBankAccountDateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayeeBankAccountDateRangeType }
     *     
     */
    public void setPayeeBankAccountDateRange(PayeeBankAccountDateRangeType value) {
        this.payeeBankAccountDateRange = value;
    }

    /**
     * Gets the value of the payeeBankAccountDateRanges property.
     * 
     * @return
     *     possible object is
     *     {@link PayeeBankAccountsType.PayeeBankAccountDateRanges }
     *     
     */
    public PayeeBankAccountsType.PayeeBankAccountDateRanges getPayeeBankAccountDateRanges() {
        return payeeBankAccountDateRanges;
    }

    /**
     * Sets the value of the payeeBankAccountDateRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayeeBankAccountsType.PayeeBankAccountDateRanges }
     *     
     */
    public void setPayeeBankAccountDateRanges(PayeeBankAccountsType.PayeeBankAccountDateRanges value) {
        this.payeeBankAccountDateRanges = value;
    }

    /**
     * Gets the value of the maintenanceComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaintenanceComment() {
        return maintenanceComment;
    }

    /**
     * Sets the value of the maintenanceComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaintenanceComment(String value) {
        this.maintenanceComment = value;
    }

    /**
     * Gets the value of the maintenanceReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeEntryInputType }
     *     
     */
    public CodeEntryInputType getMaintenanceReasonCode() {
        return maintenanceReasonCode;
    }

    /**
     * Sets the value of the maintenanceReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeEntryInputType }
     *     
     */
    public void setMaintenanceReasonCode(CodeEntryInputType value) {
        this.maintenanceReasonCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="payeeBankAccountDateRange" type="{http://www.healthedge.com/connector/schema/payeebankaccounts}PayeeBankAccountDateRangeType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "payeeBankAccountDateRange"
    })
    public static class PayeeBankAccountDateRanges {

        @XmlElement(required = true)
        protected List<PayeeBankAccountDateRangeType> payeeBankAccountDateRange;

        /**
         * Gets the value of the payeeBankAccountDateRange property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the payeeBankAccountDateRange property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPayeeBankAccountDateRange().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PayeeBankAccountDateRangeType }
         * 
         * 
         */
        public List<PayeeBankAccountDateRangeType> getPayeeBankAccountDateRange() {
            if (payeeBankAccountDateRange == null) {
                payeeBankAccountDateRange = new ArrayList<PayeeBankAccountDateRangeType>();
            }
            return this.payeeBankAccountDateRange;
        }

    }

}
