//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 *  Structured full international telephone number. 
 * 
 * <p>Java class for PhoneNumberStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhoneNumberStruct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="country" type="{http://www.codesynthesis.com/xmlns/xsstl}PhoneCountryCode"/&gt;
 *         &lt;element name="area" type="{http://www.codesynthesis.com/xmlns/xsstl}PhoneAreaCode" minOccurs="0"/&gt;
 *         &lt;element name="subscriber" type="{http://www.codesynthesis.com/xmlns/xsstl}PhoneSubscriberNumber"/&gt;
 *         &lt;element name="extension" type="{http://www.codesynthesis.com/xmlns/xsstl}PhoneExtensionNumber" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhoneNumberStruct", namespace = "http://www.codesynthesis.com/xmlns/xsstl", propOrder = {
    "country",
    "area",
    "subscriber",
    "extension"
})
public class PhoneNumberStruct {

    @XmlSchemaType(name = "unsignedShort")
    protected int country;
    @XmlSchemaType(name = "unsignedInt")
    protected Long area;
    @XmlSchemaType(name = "unsignedLong")
    protected long subscriber;
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger extension;

    /**
     * Gets the value of the country property.
     * 
     */
    public int getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     */
    public void setCountry(int value) {
        this.country = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setArea(Long value) {
        this.area = value;
    }

    /**
     * Gets the value of the subscriber property.
     * 
     */
    public long getSubscriber() {
        return subscriber;
    }

    /**
     * Sets the value of the subscriber property.
     * 
     */
    public void setSubscriber(long value) {
        this.subscriber = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExtension(BigInteger value) {
        this.extension = value;
    }

}
