//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlanSelectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlanSelectionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="enrolledPlan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="disenrollDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="disenrollReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="waiveBenefitWaitingPeriod" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlanSelectionType", namespace = "http://www.healthedge.com/connector/schema/enrollmentsparseresponse", propOrder = {
    "enrolledPlan",
    "startDate",
    "endDate",
    "disenrollDate",
    "disenrollReason",
    "waiveBenefitWaitingPeriod"
})
public class PlanSelectionType {

    protected String enrolledPlan;
    protected String startDate;
    protected String endDate;
    protected String disenrollDate;
    protected String disenrollReason;
    @XmlElement(defaultValue = "false")
    protected Boolean waiveBenefitWaitingPeriod;

    /**
     * Gets the value of the enrolledPlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrolledPlan() {
        return enrolledPlan;
    }

    /**
     * Sets the value of the enrolledPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrolledPlan(String value) {
        this.enrolledPlan = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the disenrollDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisenrollDate() {
        return disenrollDate;
    }

    /**
     * Sets the value of the disenrollDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisenrollDate(String value) {
        this.disenrollDate = value;
    }

    /**
     * Gets the value of the disenrollReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisenrollReason() {
        return disenrollReason;
    }

    /**
     * Sets the value of the disenrollReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisenrollReason(String value) {
        this.disenrollReason = value;
    }

    /**
     * Gets the value of the waiveBenefitWaitingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWaiveBenefitWaitingPeriod() {
        return waiveBenefitWaitingPeriod;
    }

    /**
     * Sets the value of the waiveBenefitWaitingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWaiveBenefitWaitingPeriod(Boolean value) {
        this.waiveBenefitWaitingPeriod = value;
    }

}
