//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreExProcedureCodeRangeConditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreExProcedureCodeRangeConditionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rangeStartProcedureCode"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="serviceReference" type="{http://www.healthedge.com/connector/schema/basetypes}ReferenceType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rangeEndProcedureCode"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="serviceReference" type="{http://www.healthedge.com/connector/schema/basetypes}ReferenceType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreExProcedureCodeRangeConditionType", propOrder = {
    "rangeStartProcedureCode",
    "rangeEndProcedureCode"
})
public class PreExProcedureCodeRangeConditionType {

    @XmlElement(required = true)
    protected PreExProcedureCodeRangeConditionType.RangeStartProcedureCode rangeStartProcedureCode;
    @XmlElement(required = true)
    protected PreExProcedureCodeRangeConditionType.RangeEndProcedureCode rangeEndProcedureCode;

    /**
     * Gets the value of the rangeStartProcedureCode property.
     * 
     * @return
     *     possible object is
     *     {@link PreExProcedureCodeRangeConditionType.RangeStartProcedureCode }
     *     
     */
    public PreExProcedureCodeRangeConditionType.RangeStartProcedureCode getRangeStartProcedureCode() {
        return rangeStartProcedureCode;
    }

    /**
     * Sets the value of the rangeStartProcedureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreExProcedureCodeRangeConditionType.RangeStartProcedureCode }
     *     
     */
    public void setRangeStartProcedureCode(PreExProcedureCodeRangeConditionType.RangeStartProcedureCode value) {
        this.rangeStartProcedureCode = value;
    }

    /**
     * Gets the value of the rangeEndProcedureCode property.
     * 
     * @return
     *     possible object is
     *     {@link PreExProcedureCodeRangeConditionType.RangeEndProcedureCode }
     *     
     */
    public PreExProcedureCodeRangeConditionType.RangeEndProcedureCode getRangeEndProcedureCode() {
        return rangeEndProcedureCode;
    }

    /**
     * Sets the value of the rangeEndProcedureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreExProcedureCodeRangeConditionType.RangeEndProcedureCode }
     *     
     */
    public void setRangeEndProcedureCode(PreExProcedureCodeRangeConditionType.RangeEndProcedureCode value) {
        this.rangeEndProcedureCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="serviceReference" type="{http://www.healthedge.com/connector/schema/basetypes}ReferenceType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "serviceReference"
    })
    public static class RangeEndProcedureCode {

        @XmlElement(required = true)
        protected ReferenceType serviceReference;

        /**
         * Gets the value of the serviceReference property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenceType }
         *     
         */
        public ReferenceType getServiceReference() {
            return serviceReference;
        }

        /**
         * Sets the value of the serviceReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenceType }
         *     
         */
        public void setServiceReference(ReferenceType value) {
            this.serviceReference = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="serviceReference" type="{http://www.healthedge.com/connector/schema/basetypes}ReferenceType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "serviceReference"
    })
    public static class RangeStartProcedureCode {

        @XmlElement(required = true)
        protected ReferenceType serviceReference;

        /**
         * Gets the value of the serviceReference property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenceType }
         *     
         */
        public ReferenceType getServiceReference() {
            return serviceReference;
        }

        /**
         * Sets the value of the serviceReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenceType }
         *     
         */
        public void setServiceReference(ReferenceType value) {
            this.serviceReference = value;
        }

    }

}
