//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreExDiagnosisCodeRangeConditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreExDiagnosisCodeRangeConditionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rangeStartDiagnosisCode"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="diagnosisReference" type="{http://www.healthedge.com/connector/schema/basetypes}ReferenceType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rangeEndDiagnosisCode"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="diagnosisReference" type="{http://www.healthedge.com/connector/schema/basetypes}ReferenceType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreExDiagnosisCodeRangeConditionType", propOrder = {
    "rangeStartDiagnosisCode",
    "rangeEndDiagnosisCode"
})
public class PreExDiagnosisCodeRangeConditionType {

    @XmlElement(required = true)
    protected PreExDiagnosisCodeRangeConditionType.RangeStartDiagnosisCode rangeStartDiagnosisCode;
    @XmlElement(required = true)
    protected PreExDiagnosisCodeRangeConditionType.RangeEndDiagnosisCode rangeEndDiagnosisCode;

    /**
     * Gets the value of the rangeStartDiagnosisCode property.
     * 
     * @return
     *     possible object is
     *     {@link PreExDiagnosisCodeRangeConditionType.RangeStartDiagnosisCode }
     *     
     */
    public PreExDiagnosisCodeRangeConditionType.RangeStartDiagnosisCode getRangeStartDiagnosisCode() {
        return rangeStartDiagnosisCode;
    }

    /**
     * Sets the value of the rangeStartDiagnosisCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreExDiagnosisCodeRangeConditionType.RangeStartDiagnosisCode }
     *     
     */
    public void setRangeStartDiagnosisCode(PreExDiagnosisCodeRangeConditionType.RangeStartDiagnosisCode value) {
        this.rangeStartDiagnosisCode = value;
    }

    /**
     * Gets the value of the rangeEndDiagnosisCode property.
     * 
     * @return
     *     possible object is
     *     {@link PreExDiagnosisCodeRangeConditionType.RangeEndDiagnosisCode }
     *     
     */
    public PreExDiagnosisCodeRangeConditionType.RangeEndDiagnosisCode getRangeEndDiagnosisCode() {
        return rangeEndDiagnosisCode;
    }

    /**
     * Sets the value of the rangeEndDiagnosisCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreExDiagnosisCodeRangeConditionType.RangeEndDiagnosisCode }
     *     
     */
    public void setRangeEndDiagnosisCode(PreExDiagnosisCodeRangeConditionType.RangeEndDiagnosisCode value) {
        this.rangeEndDiagnosisCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="diagnosisReference" type="{http://www.healthedge.com/connector/schema/basetypes}ReferenceType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "diagnosisReference"
    })
    public static class RangeEndDiagnosisCode {

        @XmlElement(required = true)
        protected ReferenceType diagnosisReference;

        /**
         * Gets the value of the diagnosisReference property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenceType }
         *     
         */
        public ReferenceType getDiagnosisReference() {
            return diagnosisReference;
        }

        /**
         * Sets the value of the diagnosisReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenceType }
         *     
         */
        public void setDiagnosisReference(ReferenceType value) {
            this.diagnosisReference = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="diagnosisReference" type="{http://www.healthedge.com/connector/schema/basetypes}ReferenceType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "diagnosisReference"
    })
    public static class RangeStartDiagnosisCode {

        @XmlElement(required = true)
        protected ReferenceType diagnosisReference;

        /**
         * Gets the value of the diagnosisReference property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenceType }
         *     
         */
        public ReferenceType getDiagnosisReference() {
            return diagnosisReference;
        }

        /**
         * Sets the value of the diagnosisReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenceType }
         *     
         */
        public void setDiagnosisReference(ReferenceType value) {
            this.diagnosisReference = value;
        }

    }

}
