//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="ServiceStatusType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Match Found"/&gt;
 *     &lt;enumeration value="No Match Found"/&gt;
 *     &lt;enumeration value="Multiple Match Found"/&gt;
 *     &lt;enumeration value="No Member Found"/&gt;
 *     &lt;enumeration value="SUCCESS"/&gt;
 *     &lt;enumeration value="FAILURE"/&gt;
 *     &lt;enumeration value="No Change"/&gt;
 *     &lt;enumeration value="ERROR"/&gt;
 *     &lt;enumeration value="Not Processed"/&gt;
 *     &lt;enumeration value="Cancel Already Processed"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ServiceStatusType")
@XmlEnum
public enum ServiceStatusType {

    @XmlEnumValue("Match Found")
    MATCH_FOUND("Match Found"),
    @XmlEnumValue("No Match Found")
    NO_MATCH_FOUND("No Match Found"),
    @XmlEnumValue("Multiple Match Found")
    MULTIPLE_MATCH_FOUND("Multiple Match Found"),
    @XmlEnumValue("No Member Found")
    NO_MEMBER_FOUND("No Member Found"),
    SUCCESS("SUCCESS"),
    FAILURE("FAILURE"),
    @XmlEnumValue("No Change")
    NO_CHANGE("No Change"),
    ERROR("ERROR"),
    @XmlEnumValue("Not Processed")
    NOT_PROCESSED("Not Processed"),
    @XmlEnumValue("Cancel Already Processed")
    CANCEL_ALREADY_PROCESSED("Cancel Already Processed");
    private final String value;

    ServiceStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceStatusType fromValue(String v) {
        for (ServiceStatusType c: ServiceStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
