//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SourceOfAuthorizationDomainType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="SourceOfAuthorizationDomainType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Enrollment application"/&gt;
 *     &lt;enumeration value="Continuation of coverage"/&gt;
 *     &lt;enumeration value="Court documents"/&gt;
 *     &lt;enumeration value="Written request"/&gt;
 *     &lt;enumeration value="Verbal request"/&gt;
 *     &lt;enumeration value="Power of Attorney"/&gt;
 *     &lt;enumeration value="Short Certificate"/&gt;
 *     &lt;enumeration value="Other Required Documentation"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SourceOfAuthorizationDomainType")
@XmlEnum
public enum SourceOfAuthorizationDomainType {

    @XmlEnumValue("Enrollment application")
    ENROLLMENT_APPLICATION("Enrollment application"),
    @XmlEnumValue("Continuation of coverage")
    CONTINUATION_OF_COVERAGE("Continuation of coverage"),
    @XmlEnumValue("Court documents")
    COURT_DOCUMENTS("Court documents"),
    @XmlEnumValue("Written request")
    WRITTEN_REQUEST("Written request"),
    @XmlEnumValue("Verbal request")
    VERBAL_REQUEST("Verbal request"),
    @XmlEnumValue("Power of Attorney")
    POWER_OF_ATTORNEY("Power of Attorney"),
    @XmlEnumValue("Short Certificate")
    SHORT_CERTIFICATE("Short Certificate"),
    @XmlEnumValue("Other Required Documentation")
    OTHER_REQUIRED_DOCUMENTATION("Other Required Documentation");
    private final String value;

    SourceOfAuthorizationDomainType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SourceOfAuthorizationDomainType fromValue(String v) {
        for (SourceOfAuthorizationDomainType c: SourceOfAuthorizationDomainType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
