//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubscriptionSubsidyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriptionSubsidyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.healthedge.com/connector/schema/basetypes}HealthRulesResourceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subscriptionHccId" type="{http://www.healthedge.com/connector/schema/basetypes}String50Type"/&gt;
 *         &lt;element name="otherBillRecipientHccId" type="{http://www.healthedge.com/connector/schema/basetypes}String50Type"/&gt;
 *         &lt;element name="benefitPlanTypeCode" type="{http://www.healthedge.com/connector/schema/basetypes}CodeEntryInputType"/&gt;
 *         &lt;element name="billingCategoryCode" type="{http://www.healthedge.com/connector/schema/basetypes}CodeEntryInputType"/&gt;
 *         &lt;element name="dateRanges"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="updateMode" type="{http://www.healthedge.com/connector/schema/basetypes}ListUpdateModeType" minOccurs="0"/&gt;
 *                   &lt;element name="dateRange" type="{http://www.healthedge.com/connector/schema/subsidy}SubsidyDateRangeType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionSubsidyType", namespace = "http://www.healthedge.com/connector/schema/subsidy", propOrder = {
    "subscriptionHccId",
    "otherBillRecipientHccId",
    "benefitPlanTypeCode",
    "billingCategoryCode",
    "dateRanges"
})
public class SubscriptionSubsidyType
    extends HealthRulesResourceType
{

    @XmlElement(required = true)
    protected String subscriptionHccId;
    @XmlElement(required = true)
    protected String otherBillRecipientHccId;
    @XmlElement(required = true)
    protected CodeEntryInputType benefitPlanTypeCode;
    @XmlElement(required = true)
    protected CodeEntryInputType billingCategoryCode;
    @XmlElement(required = true)
    protected SubscriptionSubsidyType.DateRanges dateRanges;

    /**
     * Gets the value of the subscriptionHccId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionHccId() {
        return subscriptionHccId;
    }

    /**
     * Sets the value of the subscriptionHccId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionHccId(String value) {
        this.subscriptionHccId = value;
    }

    /**
     * Gets the value of the otherBillRecipientHccId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherBillRecipientHccId() {
        return otherBillRecipientHccId;
    }

    /**
     * Sets the value of the otherBillRecipientHccId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherBillRecipientHccId(String value) {
        this.otherBillRecipientHccId = value;
    }

    /**
     * Gets the value of the benefitPlanTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeEntryInputType }
     *     
     */
    public CodeEntryInputType getBenefitPlanTypeCode() {
        return benefitPlanTypeCode;
    }

    /**
     * Sets the value of the benefitPlanTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeEntryInputType }
     *     
     */
    public void setBenefitPlanTypeCode(CodeEntryInputType value) {
        this.benefitPlanTypeCode = value;
    }

    /**
     * Gets the value of the billingCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeEntryInputType }
     *     
     */
    public CodeEntryInputType getBillingCategoryCode() {
        return billingCategoryCode;
    }

    /**
     * Sets the value of the billingCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeEntryInputType }
     *     
     */
    public void setBillingCategoryCode(CodeEntryInputType value) {
        this.billingCategoryCode = value;
    }

    /**
     * Gets the value of the dateRanges property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionSubsidyType.DateRanges }
     *     
     */
    public SubscriptionSubsidyType.DateRanges getDateRanges() {
        return dateRanges;
    }

    /**
     * Sets the value of the dateRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionSubsidyType.DateRanges }
     *     
     */
    public void setDateRanges(SubscriptionSubsidyType.DateRanges value) {
        this.dateRanges = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="updateMode" type="{http://www.healthedge.com/connector/schema/basetypes}ListUpdateModeType" minOccurs="0"/&gt;
     *         &lt;element name="dateRange" type="{http://www.healthedge.com/connector/schema/subsidy}SubsidyDateRangeType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "updateMode",
        "dateRange"
    })
    public static class DateRanges {

        @XmlSchemaType(name = "string")
        protected ListUpdateModeType updateMode;
        @XmlElement(required = true)
        protected List<SubsidyDateRangeType> dateRange;

        /**
         * Gets the value of the updateMode property.
         * 
         * @return
         *     possible object is
         *     {@link ListUpdateModeType }
         *     
         */
        public ListUpdateModeType getUpdateMode() {
            return updateMode;
        }

        /**
         * Sets the value of the updateMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link ListUpdateModeType }
         *     
         */
        public void setUpdateMode(ListUpdateModeType value) {
            this.updateMode = value;
        }

        /**
         * Gets the value of the dateRange property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dateRange property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDateRange().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SubsidyDateRangeType }
         * 
         * 
         */
        public List<SubsidyDateRangeType> getDateRange() {
            if (dateRange == null) {
                dateRange = new ArrayList<SubsidyDateRangeType>();
            }
            return this.dateRange;
        }

    }

}
