//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 03:47:37 PM IST 
//


package com.enrollment.EmassWebService.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkFlowActionCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="WorkFlowActionCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Continue CVC"/&gt;
 *     &lt;enumeration value="Cancel CVC"/&gt;
 *     &lt;enumeration value="Fulfill With Code"/&gt;
 *     &lt;enumeration value="Review/Repair"/&gt;
 *     &lt;enumeration value="Repair"/&gt;
 *     &lt;enumeration value="Review"/&gt;
 *     &lt;enumeration value="Repricing"/&gt;
 *     &lt;enumeration value="Requires Funding"/&gt;
 *     &lt;enumeration value="External System"/&gt;
 *     &lt;enumeration value="Requires Funding Request Pre-Approval"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "WorkFlowActionCodeType")
@XmlEnum
public enum WorkFlowActionCodeType {

    @XmlEnumValue("Continue CVC")
    CONTINUE_CVC("Continue CVC"),
    @XmlEnumValue("Cancel CVC")
    CANCEL_CVC("Cancel CVC"),
    @XmlEnumValue("Fulfill With Code")
    FULFILL_WITH_CODE("Fulfill With Code"),
    @XmlEnumValue("Review/Repair")
    REVIEW_REPAIR("Review/Repair"),
    @XmlEnumValue("Repair")
    REPAIR("Repair"),
    @XmlEnumValue("Review")
    REVIEW("Review"),
    @XmlEnumValue("Repricing")
    REPRICING("Repricing"),
    @XmlEnumValue("Requires Funding")
    REQUIRES_FUNDING("Requires Funding"),
    @XmlEnumValue("External System")
    EXTERNAL_SYSTEM("External System"),
    @XmlEnumValue("Requires Funding Request Pre-Approval")
    REQUIRES_FUNDING_REQUEST_PRE_APPROVAL("Requires Funding Request Pre-Approval");
    private final String value;

    WorkFlowActionCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WorkFlowActionCodeType fromValue(String v) {
        for (WorkFlowActionCodeType c: WorkFlowActionCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
